# Introduction to Data Science 2025

# Week 1

## Exercise 1 | Matrix warm-up
<span style="background-color: #ccfff2"> *Note: You can find tutorials for NumPy and Pandas under 'Useful tutorials' in the course material.*</span>

One of the most useful properties of any scientific programming language (Python with NumPy, R, Julia, etc) is that they allow us to work with matrices efficiently. Let's learn more about these features!

### 1.1 Basics

1. Let's start by creating two arrays <span style="background-color: #ccfff2"> A</span> and <span style="background-color: #ccfff2"> B</span> which each have the integers <span style="background-color: #ccfff2"> 0, 1, 2, ..., 1e7-1</span>. Use the normal arrays or lists of the programming language you are using, e.g. *list* or *[ ]* or *numpy.array()* in Python.

In [11]:
# Use this cell for your code
import numpy as np

A = list(range(1, int(1e7-1)))
B = list(range(1, int(1e7-1)))




2. Create a function that uses a <span style="background-color: #ccfff2"> for loop</span> or equivalent to return a new array <span style="background-color: #ccfff2"> C</span>, which contains the <span style="background-color: #ccfff2"> element-wise sum of *A* and *B*</span>, e.g. C should contain the integers <span style="background-color: #ccfff2"> 0, 2, 4, etc</span>.

In [ ]:
def add_with_for(A,B):
    C = []
    for n in range(len(A)):
        C.append(A[n] + B[n])
    return C



3. Next, let's create another function that uses NumPy (or equivalent) to do the same. To try it out, allocate two arrays (e.g. using <span style="background-color: #ccfff2"> np.array</span> in NumPy) and add the arrays together using your function. Don't use loops, instead, find out how to add the two arrays directly. What do you notice in comparison to the previous function?

In [2]:
# Use this cell for your code
A_np = np.array(A)
B_np = np.array(B)

d = A_np + B_np
print(d)


[       2        4        6 ... 19999992 19999994 19999996]


### 1.2 Array manipulation

<span style="background-color: #ccfff2"> *Note: for the following exercises, only use NumPy or equivalent functions. Don't use any loops.* </span>
1. Create the following array:

*[hint: <span style="background-color: #ccfff2"> np.reshape</span>]*

In [17]:
# array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
#        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
#        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
#        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
#        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
#        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
#        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
#        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
#        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
#        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [18]:
# Use this cell for your code
array = np.arange(100).reshape(10,10)
print(array)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


2. Create the following array:

In [19]:
# array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

In [20]:
# Use this cell for your code
array1 = np.tile([0.,1.,], (10,5))
s = np.array2string(array1, separator=', ')
print(f'array({s})')

array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
 [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
 [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
 [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
 [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
 [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
 [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
 [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
 [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
 [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])


3. Create the following array (D):

In [21]:
# array([[0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

In [22]:
# Use this cell for your code
n = 10
D = np.ones((n, n)) - np.eye(n)
print(D)

[[0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]]


4. Create the following array (E):

In [23]:
# array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [0., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [24]:
# Use this cell for your code
n = 10
E = np.ones((n, n)) - np.fliplr(np.eye(n))
print(E)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5. Call the last two matrices <span style="background-color: #ccfff2">D</span> and <span style="background-color: #ccfff2">E</span>, respectively. Show that the determinant of their product (matrix multiplication) is the same as the product of their determinants. That is calculate both <span style="background-color: #ccfff2">det(DE)</span> and <span style="background-color: #ccfff2">det(D) * det(E)</span>, and show that they are the same. Is it a coincidence? (I think not) The product of the determinants (or the determinant of the product) should be -81.

In [29]:
# Use this cell for your code
det_D = np.linalg.det(D)
det_E = np.linalg.det(E)
det_DE = np.linalg.det(D @ E)
prod_det = det_D * det_E

print(prod_det)

-81.0


-- *Use this markdown cell for your written answer* --

### 1.3 Slicing

Array slicing is a powerful way to extract data from an array. Let's practice array slicing with the following exercises!

1. Load the [California housing dataset](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_california_housing.html). The data should be a matrix of shape <span style="background-color: #ccfff2">(20640, 8)</span>, that is 20640 rows and 8 columns. Use the <span style="background-color: #ccfff2">.shape</span> attribute of NumPy arrays to verify this. Here's a [description of the fields](https://scikit-learn.org/stable/datasets/real_world.html#california-housing-dataset).

In [ ]:
# Use this cell for your code
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
X = housing.data

print(X.shape)


(20640, 8)
[[   8.3252       41.            6.98412698 ...    2.55555556
    37.88       -122.23      ]
 [   8.3014       21.            6.23813708 ...    2.10984183
    37.86       -122.22      ]
 [   7.2574       52.            8.28813559 ...    2.80225989
    37.85       -122.24      ]
 ...
 [   1.7          17.            5.20554273 ...    2.3256351
    39.43       -121.22      ]
 [   1.8672       18.            5.32951289 ...    2.12320917
    39.43       -121.32      ]
 [   2.3886       16.            5.25471698 ...    2.61698113
    39.37       -121.24      ]]


2. Select rows where the average number of bedrooms <span style="background-color: #ccfff2">(AveBedrms)</span> is higher than 2. The first few row indices should be <span style="background-color: #ccfff2">710,  1023,  1024, ...</span> (zero-indexed). Count these houses - how many rows are selected? *[hint: <span style="background-color: #ccfff2">np.where</span>]*

In [13]:
# Use this cell for your code
res = np.where(X[:, 3] > 2)
print(res)
print(len(res[0]))

(array([  710,  1023,  1024,  1030,  1102,  1233,  1234,  1235,  1236,
        1238,  1239,  1240,  1566,  1867,  1871,  1872,  1879,  1881,
        1889,  1901,  1906,  1910,  1911,  1912,  1913,  1914,  1925,
        1926,  1978,  1979,  2392,  2395,  2396,  2397,  2398,  2510,
        2511,  2643,  2656,  2763,  2768,  2776,  2778,  3014,  3086,
        3095,  3258,  3292,  3293,  3313,  3314,  3334,  3349,  3350,
        9193,  9423,  9431,  9451,  9634,  9669,  9671,  9672,  9675,
        9676,  9678,  9679,  9680,  9681,  9682,  9683, 10067, 10076,
       10077, 10078, 10079, 10080, 10081, 10082, 10083, 10084, 10405,
       11705, 11706, 11707, 11708, 11709, 11710, 11711, 11713, 11714,
       11715, 11716, 11717, 11719, 11720, 11721, 11722, 11723, 11724,
       11725, 11729, 11831, 11832, 11833, 11834, 11847, 11848, 11849,
       11850, 11862, 11865, 11866, 11867, 11869, 11870, 12136, 12303,
       12305, 12306, 12307, 12324, 12325, 12344, 12349, 12351, 12354,
       12359, 12361

3. Select the rows where the median house age (i.e. median in each block group) <span style="background-color: #ccfff2">(HouseAge)</span> is between 1 and 3 years (inclusive). There should be **124** of these.

In [18]:
# Use this cell for your code
res = np.where((X[:, 1] >= 1 ) & (X[:, 1] <= 3))
print(len(res[0]))

124


4. Find the mean of the block group population <span style="background-color: #ccfff2">(Population)</span> for homes whose median value is more than 25000 USD (the target variable). It should be around **1425.68**.

In [23]:
# Use this cell for your code
y = housing.target
mask = y > 0.25
res = X[mask, 4]
res = np.mean(res)
print(res)

1425.6833737275813


## Exercise 2 | Working with text data

Next, let's look into some text data. We will be looking into Amazon reviews, and the necessary steps to transform a raw dataset into a format more suitable for prediction tasks.

1. Download the automotive 5-core dataset from [here](https://jmcauley.ucsd.edu/data/amazon_v2/categoryFilesSmall/Automotive_5.json.gz). Next, you can extract the data in <span style="background-color: #ccfff2">JSON</span> format. You can also download one of the bigger ones, if you are feeling ambitious. Open the JSON file. Access the <span style="background-color: #ccfff2">reviewText</span> field, which contains the unstructured review text written by the user.

For instance, the first review reads as follows: 

*'After I wrote the below review, the manufacturer contacted me and explained how to use this.  Instead of the (current) picture on Amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally. [...]'*

In [ ]:
# Use this cell for your code
import json

filepath = 'Automotive_5.json'
data = []
with open(filepath, 'r') as file:
    for line in file:
        data.append(json.loads(line))
     


print(data[0]["reviewText"])


2. Next, let's follow some steps to normalize the text data.

When dealing with natural language, it is important to notice that while, for example, the words "Copper" and "copper" are represented by two different strings, they have the same meaning. When applying statistical methods on this data, it is useful to ensure that words with the same meaning are represented by the same string.

* <span style="background-color: #ccfff2">Downcasing</span>: Let's first downcase the contents of the <span style="background-color: #ccfff2">reviewText</span> field.

Now the first review should be:

*'after i wrote the below review, the manufacturer contacted me and explained how to use this.  instead of the (current) picture on amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally.'*

In [11]:
# Use this cell for your code
reviews = [d["reviewText"] for d in data if "reviewText" in d]

reviews = [r.lower() for r in reviews]  
print(reviews[0])

after i wrote the below review, the manufacturer contacted me and explained how to use this.  instead of the (current) picture on amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally.  then the charge / sync cable goes through the hole and you can charge from the side.  when used in landscape position this stand does make more sense so i'm upgrading this review from 2 stars to 4 stars (which i rarely do, but in this case user error) with a star off for lack of documentation.  manufacturer has said he will include directions and i would also encourage him to update the photos on amazon with more examples of how this can be used.  the wood quality is indeed good and it's a sturdy little stand.  i'm trying to think of when i'd actually use this stand... perhaps for facetime chats.  i also think it would be useful for someone in an open office environment if they want to keep their phone on their desk and see alerts / notifications easi

3. Let's continue with punctuation and stop word removal. Stop words are words like "and", "the", etc. They are usually very common words that have little to do with the actual content matter. There's plenty openly available lists of stop words for almost any (natural) language.

* <span style="background-color: #ccfff2">Punctuation and stop-word removal</span>: Let's now remove all punctuation, as well as the stop words. You can find a stop word list for English, e.g. [here](https://gist.github.com/xldrkp/4a3b1a33f10d37bedbe0068f2b4482e8#file-stopwords-en-txt).*(use the link to download a txt of english stopwords)* Save the stopwords in the file as "stopwords-en.txt".

First review at this point reads as: 

*'wrote review manufacturer contacted explained current picture amazon phone vertically stand phone horizontally'*

In [14]:
# Use this cell for your code
import re
reviews = [re.sub(r"[^a-z\s]", " ", r) for r in reviews]      
with open("stopwords-en.txt", "r") as f:
    stopwords = set(w.strip().lower() for w in f if w.strip())

reviews = [
    " ".join([word for word in r.split() if word not in stopwords])
    for r in reviews
]

print(reviews[0])

wrote review manufacturer contacted explained current picture amazon phone placed vertically actually stand phone placed horizontally charge sync cable goes hole charge used landscape position stand does make sense m upgrading review stars stars rarely case user error star lack documentation manufacturer said include directions encourage update photos amazon examples used wood quality good s sturdy little stand m trying think d actually stand facetime chats think useful open office environment want phone desk alerts notifications easily hope updated review helps original review throwing stand garbage s crafted nice wood functional near tell does come instructions product description confusing english poorly translated chinese iphone sits stand just fine s stand way plug plug stand blocks turn iphone plug just looks strange m sure hole stand supposed included plastic feet instructions affixed stand began wobble figure work thing post review far m concerned box experience terrible sorry 

4. Let's continue with stemming. For example, while the words "swims" and "swim" are different strings, they both refer to swimming. [Stemming](https://en.wikipedia.org/wiki/Stemming) refers to the process of mapping words from their inflected form to their base form, for instance: swims -> swim.

* <span style="background-color: #ccfff2">Stemming</span>: Apply a stemmer on the paragraphs, so that inflected forms are mapped to the base form. For example, for Python the popular natural language toolkit [nltk](http://www.nltk.org/howto/stem.html) has an easy to use stemmer. In case you are using R, you can try the [Snowball stemmer](https://www.rdocumentation.org/packages/corpus/versions/0.10.2/topics/stem_snowball). You can find out how to install nltk from [here](https://www.nltk.org/install.html). It will take a while to run! So, grab a coffee and wait :D

Finally, after stemming: 

*'wrote review manufactur contact explain current pictur amazon phone vertic stand phone horizont'*

In [19]:
# Use this cell for your code
from nltk.stem import*
import nltk
nltk.download('punkt')
stemmer = PorterStemmer()
stemmer = PorterStemmer()
reviews = [
    " ".join([stemmer.stem(word) for word in r.split()])
    for r in reviews
]

print("After stemming:", reviews[0])


[nltk_data] Downloading package punkt to /home/haarhaar/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


After stemming: wrote review manufactur contact explain current pictur amazon phone place vertic actual stand phone place horizont charg sync cabl goe hole charg use landscap posit stand doe make sens m upgrad review star star rare case user error star lack document manufactur said includ direct encourag updat photo amazon exampl use wood qualiti good s sturdi littl stand m tri think d actual stand facetim chat think use open offic environ want phone desk alert notif easili hope updat review help origin review throw stand garbag s craft nice wood function near tell doe come instruct product descript confus english poorli translat chines iphon sit stand just fine s stand way plug plug stand block turn iphon plug just look strang m sure hole stand suppos includ plastic feet instruct affix stand began wobbl figur work thing post review far m concern box experi terribl sorri recommend sampl provid exchang honest review


5. Finally, filter the data by selecting reviews where the field <span style="background-color: #ccfff2">overall</span> is 4 or 5, and store the review texts in a file named <span style="background-color: #ccfff2">pos.txt</span>. Similarly, select reviews with rating 1 or 2 and store them in a file named <span style="background-color: #ccfff2">neg.txt</span>. Ignore the reviews with overall rating 3. Each line in the two files should contain exactly one preprocessed review text without the rating.

In [ ]:
# Use this cell for your code

pos_path = "pos.txt"
neg_path = "neg.txt"

pos_out = open(pos_path, "w", encoding="utf-8")
neg_out = open(neg_path, "w", encoding="utf-8")

pos_count = 0
neg_count = 0
skipped = 0

i = 0  

for d in data:
    if "reviewText" not in d:
        continue  
    text = reviews[i].strip()
    i += 1  
    if not text:
        skipped += 1
        continue

    if "overall" not in d:
        skipped += 1
        continue

    try:
        rating = int(d["overall"])
    except Exception:
        skipped += 1
        continue

    if rating == 3:
        continue  

    if rating >= 4:
        pos_out.write(text + "\n")
        pos_count += 1
    elif rating <= 2:
        neg_out.write(text + "\n")
        neg_count += 1
    else:
        skipped += 1

pos_out.close()
neg_out.close()

print(f"Done. Wrote {pos_count} lines to {pos_path} and {neg_count} lines to {neg_path}. Skipped: {skipped}.")


Done. Wrote 1470185 lines to pos.txt and 132123 lines to neg.txt. Skipped: 5945.


## Exercise 3 | SQL basics

Next, let's take a refresher on the basics of SQL. In this exercise, you will be working on the simplified Northwind 2000 SQLite database. You can download the database from Kaggle [here](https://courses.mooc.fi/api/v0/files/course/f92ffc32-2dd4-421d-87f3-c48800422cc5/files/VEKX2bxGCDGyojG902gmYZTXCnrAQw.zip).

To test your SQL queries and complete the exercise, you can download and install SQLite if you don't yet have it installed.

Please write SQL queries for the tasks on the simplified Northwind 2000 SQLite database.

1. List the first name, last name, and hire date of all employees hired after January 1st, 1994.

2. Count how many orders each customer has placed.

3. Find the names of all customers who have ordered the product "Chai".

4. Find all orders that have been placed but not yet shipped.

5. Find the customer who has placed the most orders.

In [ ]:
1.
sqlite> SELECT FirstName, Lastname, HireDate FROM Employees WHERE HireDate > '1994-01-01' ORDER BY HireDate;
FirstName  LastName   HireDate  
---------  ---------  ----------
Robert     King       1994-01-02
Laura      Callahan   1994-03-05
Anne       Dodsworth  1994-11-15
2.
sqlite> SELECT c.CustomerID,
       c.CompanyName,
       COUNT(o.OrderID) AS order_count
FROM customers AS c
LEFT JOIN orders AS o
  ON o.CustomerID = c.CustomerID
GROUP BY c.CustomerID, c.CompanyName
ORDER BY order_count DESC, c.CompanyName;
ORDER BY order_count DESC, c.CompanyName;

CustomerID  CompanyName                           order_count
----------  ------------------------------------  -----------
SAVEA       Save-a-lot Markets                    31         
ERNSH       Ernst Handel                          30         
QUICK       QUICK-Stop                            28         
FOLKO       Folk och fä HB                        19         
HUNGO       Hungry Owl All-Night Grocers          19         
BERGS       Berglunds snabbköp                    18         
HILAA       HILARION-Abastos                      18         
RATTC       Rattlesnake Canyon Grocery            18         
BONAP       Bon app'                              17         
FRANK       Frankenversand                        15         
LEHMS       Lehmanns Marktstand                   15         
WARTH       Wartian Herkku                        15         
BOTTM       Bottom-Dollar Markets                 14         
HANAR       Hanari Carnes                         14         
KOENE       Königlich Essen                       14         
LILAS       LILA-Supermercado                     14         
LAMAI       La maison d'Asie                      14         
WHITC       White Clover Markets                  14         
AROUT       Around the Horn                       13         
MEREP       Mère Paillarde                        13         
QUEEN       Queen Cozinha                         13         
LINOD       LINO-Delicateses                      12         
REGGC       Reggiani Caseifici                    12         
SUPRD       Suprêmes délices                      12         
BLONP       Blondesddsl père et fils              11         
GREAL       Great Lakes Food Market               11         
RICAR       Ricardo Adocicados                    11         
VAFFE       Vaffeljernet                          11         
BSBEV       B's Beverages                         10         
WANDK       Die Wandernde Kuh                     10         
GODOS       Godos Cocina Típica                   10         
ISLAT       Island Trading                        10         
MAGAA       Magazzini Alimentari Riuniti          10         
OLDWO       Old World Delicatessen                10         
OTTIK       Ottilies Käseladen                    10         
PICCO       Piccolo und mehr                      10         
RICSU       Richter Supermarkt                    10         
TORTU       Tortuga Restaurante                   10         
VICTE       Victuailles en stock                  10         
GOURL       Gourmet Lanchonetes                   9          
QUEDE       Que Delícia                           9          
SEVES       Seven Seas Imports                    9          
SPLIR       Split Rail Beer & Ale                 9          
WELLI       Wellington Importadora                9          
CHOPS       Chop-suey Chinese                     8          
EASTC       Eastern Connection                    8          
FURIB       Furia Bacalhau e Frutos do Mar        8          
LONEP       Lonesome Pine Restaurant              8          
ANTON       Antonio Moreno Taquería               7          
BLAUS       Blauer See Delikatessen               7          
FAMIA       Familia Arquibaldo                    7          
MAISD       Maison Dewey                          7          
SIMOB       Simons bistro                         7          
WILMK       Wilman Kala                           7          
WOLZA       Wolski  Zajazd                        7          
ALFKI       Alfreds Futterkiste                   6          
CACTU       Cactus Comidas para llevar            6          
DRACD       Drachenblut Delikatessen              6          
FRANS       Franchi S.p.A.                        6          
PERIC       Pericles Comidas clásicas             6          
SANTG       Santé Gourmet                         6          
TOMSP       Toms Spezialitäten                    6          
TRADH       Tradição Hipermercados                6          
COMMI       Comércio Mineiro                      5          
FOLIG       Folies gourmandes                     5          
GALED       Galería del gastrónomo                5          
HUNGC       Hungry Coyote Import Store            5          
MORGK       Morgenstern Gesundkost                5          
OCEAN       Océano Atlántico Ltda.                5          
PRINI       Princesa Isabel Vinhos                5          
RANCH       Rancho grande                         5          
ROMEY       Romero y tomillo                      5          
VINET       Vins et alcools Chevalier             5          
ANATR       Ana Trujillo Emparedados y helados    4          
DUMON       Du monde entier                       4          
LACOR       La corne d'abondance                  4          
LETSS       Let's Stop N Shop                     4          
SPECD       Spécialités du monde                  4          
THEBI       The Big Cheese                        4          
BOLID       Bólido Comidas preparadas             3          
CONSH       Consolidated Holdings                 3          
FRANR       France restauration                   3          
LAUGB       Laughing Bacchus Wine Cellars         3          
NORTS       North/South                           3          
THECR       The Cracker Box                       3          
TRAIH       Trail's Head Gourmet Provisioners     3          
GROSR       GROSELLA-Restaurante                  2          
LAZYK       Lazy K Kountry Store                  2          
CENTC       Centro comercial Moctezuma            1          
FISSA       FISSA Fabrica Inter. Salchichas S.A.  0          
PARIS       Paris spécialités                     0  

3.
sqlite> SELECT DISTINCT c.CompanyName
FROM customers AS c
JOIN orders AS o
  ON o.CustomerID = c.CustomerID
JOIN OrderDetails AS od
  ON od.OrderID = o.OrderID
JOIN products AS p
  ON p.ProductID = od.ProductID
WHERE p.ProductName = 'Chai'
ORDER BY c.CompanyName;
CompanyName                 
----------------------------
Berglunds snabbköp          
Blondesddsl père et fils    
Bottom-Dollar Markets       
Chop-suey Chinese           
Die Wandernde Kuh           
Du monde entier             
Eastern Connection          
Godos Cocina Típica         
Great Lakes Food Market     
HILARION-Abastos            
Hungry Owl All-Night Grocers
LINO-Delicateses            
La maison d'Asie            
Lehmanns Marktstand         
Lonesome Pine Restaurant    
Mère Paillarde              
North/South                 
Pericles Comidas clásicas   
Princesa Isabel Vinhos      
QUICK-Stop                  
Queen Cozinha               
Rattlesnake Canyon Grocery  
Save-a-lot Markets          
Seven Seas Imports          
Suprêmes délices            
The Cracker Box             
Tortuga Restaurante         
Wartian Herkku              
Wellington Importadora      
Wilman Kala                 
Wolski  Zajazd  

4. 
sqlite> SELECT OrderID, CustomerID, OrderDate
FROM orders
WHERE ShippedDate IS NULL
ORDER BY OrderDate;
OrderID  CustomerID  OrderDate              
-------  ----------  -----------------------
11008    ERNSH       1998-04-08 00:00:00.000
11019    RANCH       1998-04-13 00:00:00.000
11039    LINOD       1998-04-21 00:00:00.000
11040    GREAL       1998-04-22 00:00:00.000
11045    BOTTM       1998-04-23 00:00:00.000
11051    LAMAI       1998-04-27 00:00:00.000
11054    CACTU       1998-04-28 00:00:00.000
11058    BLAUS       1998-04-29 00:00:00.000
11059    RICAR       1998-04-29 00:00:00.000
11061    GREAL       1998-04-30 00:00:00.000
11062    REGGC       1998-04-30 00:00:00.000
11065    LILAS       1998-05-01 00:00:00.000
11068    QUEEN       1998-05-04 00:00:00.000
11070    LEHMS       1998-05-05 00:00:00.000
11071    LILAS       1998-05-05 00:00:00.000
11072    ERNSH       1998-05-05 00:00:00.000
11073    PERIC       1998-05-05 00:00:00.000
11074    SIMOB       1998-05-06 00:00:00.000
11075    RICSU       1998-05-06 00:00:00.000
11076    BONAP       1998-05-06 00:00:00.000
11077    RATTC       1998-05-06 00:00:00.000
5.
  SELECT c.CustomerID,
         c.CompanyName,
         COUNT(o.OrderID) AS order_count
  FROM customers AS c
  JOIN orders AS o
    ON o.CustomerID = c.CustomerID
  GROUP BY c.CustomerID, c.CompanyName
)
SELECT CustomerID, CompanyName, order_count
FROM counts
WHERE order_count = (SELECT MAX(order_count) FROM counts);

CustomerID  CompanyName         order_count
----------  ------------------  -----------
SAVEA       Save-a-lot Markets  31    

**Remember to submit your solutions. You can return this Jupyter notebook (.ipynb) or .py, .R, etc depending on your programming preferences. Remember to also submit your SQL queries. No need to submit the text files for the programming exercises.**